### ISSUE TITLE
Use "lastest" URL in iso_checksum_url

### ISSUE THREAD

**Issue by fishilico** [elasticdog/packer-arch#52]
Hello,
When running ``wrapacker`` I get:

    * No checksum for "archlinux-2016.11.01-dual.iso" found at:
    https://mirrors.kernel.org/archlinux/iso/2016.10.01/sha1sums.txt

This is because ``iso_url`` gets automatically updated to the latest iso image, but not ``iso_checksum_url``. This is fixed when I modify ``arch-template.json`` to have (instead of the hard-code 2016.10.01 date):

    "iso_checksum_url": "https://mirrors.kernel.org/archlinux/iso/latest/sha1sums.txt",

Could you please fix this? Also this would make monthly update commits no longer necessary.

**Comment by elasticdog** [comment]
I'm slightly confused how that error was thrown, as when using the `wrapacker` script, both the ISO and checksum are sourced from the latest *sha1sums.txt* file. If you look at the URL from the error message, that checksum file loads for me and definitely has a matching value, although the wrapper script should always use a URL that looks like `${MIRROR}/iso/latest/sha1sums.txt`. That was one of the main motivations behind writing the wrapper script in the first place, and you can see [the source](https://github.com/elasticdog/packer-arch/blob/5dd890c2fa6b510b3297e52ec10fabd862bd1c1f/wrapacker#L234-L238) where the `ISO_CHECKSUM` variable is set using that pattern.

The reason we can't just update the `iso_checksum_url` in the actual packer template, is that the `iso_url` always has a date embedded in the name itself, and since the checksum must match, we do manual updates on a monthly basis to ensure they're in lockstep. Otherwise when a new release came out upstream, the template would reference the older release ISO, but the latest checksum file, and thus you'd have a failure due to the mismatch.

If you have some more details on the command you were running or debugging output so I can duplicate the problem, I can definitely look into this further; but for now I'll close this issue out as I think the default behavior should already match your expectations.

**Comment by elasticdog** [comment]
Actually, it looks like something is up...I should have verified that things were working locally, which I hadn't done in a while. We still can't change the template due to the above reasons, but give me a bit to look into why the checksum error message is being thrown.

**Comment by fishilico** [comment]
The wrapper is using ``-var "iso_checksum=$ISO_CHECKSUM"`` but this variable is not used in the template. Replacing it with ``-var "iso_checksum_url=${MIRROR}/iso/latest/sha1sums.txt"`` should fix the issue.

**Comment by elasticdog** [comment]
...and I apologize that I overlooked the date `10` vs `11` mismatch in your original error message. If you look at what wrapacker is actually generating, the command looks correct:

```
packer build -only=virtualbox-iso -var iso_url=https://mirrors.kernel.org/archlinux/iso/latest/archlinux-2016.11.01-dual.iso -var iso_checksum=5f7ceacd97d730a007ef277847713c6031b632ec -var ssh_timeout=20m arch-template.json
```

...so I suspect that the precedence rules for `iso_checksum` versus `iso_checksum_url` are no longer functioning as they're [documented upstream](https://www.packer.io/docs/builders/virtualbox-iso.html#iso_checksum), so the checksum URL that's in the template isn't being ignored.

It looks like we can fix this somewhat trivially by not parsing out the actual checksum ourselves, and instead just having wrapacker override the `iso_checksum_url` pointing to latest.

**Comment by fishilico** [comment]
In order to use ``iso_checksum``, you need to define them in each builder blocks of the template. If I add ``"iso_checksum": "",`` in ``variables`` and ``"iso_checksum": "{{ user `iso_checksum` }}",`` in each providers, the wrapper works fine again.

**Comment by elasticdog** [comment]
Right...I'm actually confused about how this was working previously. Either I've always run Packer with an updated *arch-template.json* file (which I don't think is the case), or Packer used to pay attention to the `iso_checksum` variable provided on the command line even though it wasn't explicitly in the builder section of the template. Odd indeed.

Either way, I pushed the change so we can just consistently use the  `iso_checksum_url` and never set the actual checksum ourselves. Thanks for filing the issue!
