### ISSUE TITLE
Error on retrieving checksums

### ISSUE THREAD

**Issue by samegens** [elasticdog/packer-arch#78]
Hi!

I just cloned this repo and executed

```packer build -only=virtualbox-iso arch-template.json```

And I got this error:

```Error: Failed to prepare build: "virtualbox-iso"

1 error(s) occurred:

* Error downloading checksum file: bad response code: 404 in
"file:https://mirrors.kernel.org/archlinux/iso/2022.08.01/sha1sums.txt"
```

When looking at https://mirrors.edge.kernel.org/archlinux/iso/ I see that there is indeed no 2022.08.01 directory, it's 2022.08.05 for some reason. However there's also a 'latest' directory. When I change the urls to

```        
        "iso_url": "https://mirrors.kernel.org/archlinux/iso/latest/archlinux-x86_64.iso",
        "iso_checksum_url": "https://mirrors.kernel.org/archlinux/iso/latest/sha1sums.txt",
```

It works fine, but the final box has a slightly incorrect name, packer_arch_virtualbox_2022.08.01.iso instead of packer_arch_virtualbox_2022.08.05.iso (which is fine for my purpose).

Hope this helps!

Cheers,

Sebastiaan

**Comment by elasticdog** [comment]
Hey Sebastiaan, thank you for the report. Since the ISO URLs do change regularly and not always at the expected cadence, I would pretty much always suggest using [the `wrapacker` script](https://github.com/elasticdog/packer-arch#wrapacker) from the top level of the repo to ensure that the proper URLs get put into place…it parses the files from the “latest” directory for you. Let me know if that doesn’t work as expected, but I think it should help. Cheers!
